---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.medium
    release: xenial
    stack_name: "{{ region }}-{{ stack }}-{{ environs }}-{{ spoke }}"
    uregion: "{{ region | regex_replace('-', '_') }}"
  tasks:
  - name: "Stack facts for {{ region }}-infra-{{ environs }}-{{spoke }}"
    cloudformation_stack_facts:
      stack_name: "{{ region }}-infra-{{ environs }}-{{ spoke }}"
      region: "{{ region }}"
    register: stack_infra
  - name: "Provision {{ stack_name }}"
    cloudformation:
      region: "{{ region }}"
      stack_name: "{{ stack_name }}"
      state: "{{ stack_state }}"
      template: "{{ base_dir }}/cf_stacks/{{ stack }}.yml"
      template_format: yaml
      template_parameters:
        AppName: "{{ stack }}"
        CohorsSecurityGroup: "{{ stack_infra.stack_outputs.SecurityGroup }}"
        Environs: "{{ environs }}"
        KeyName: "{{ key[environs][uregion] }}"
        ImageId: "{{ ami[release][uregion] }}"
        InstanceType: "{{ instance_type }}"
        PrivateDnsZone: "{{ private_dns_zone }}"
        Region: "{{ region }}"
        Spoke: "{{ spoke }}"
        SubnetId: "{{ stack_infra.stack_outputs.SecondPrivateSubnet }}"
