---
- hosts: localhost
  connection: local
  gather_facts: False
#  vars_files:
#    - {{ base_dir }}/group_vars/all
  vars:
    release: xenial
    stela_name: "{{ region }}-{{ stela }}-{{ environs }}"
    uregion: "{{ region | regex_replace('-', '_') }}"
  tasks:
  - name: "Provision {{ stela_name }}"
    cloudformation:
      region: "{{ region }}"
      stack_name: "{{ stela_name }}"
      state: "{{stela_state }}"
      template: "{{ base_dir }}/cf/{{ stela_name }}.cftemplate"
#      template_format: yaml
      template_parameters:
        AppName: "{{ stela }}"
        AZ1: "{{ availability_zone[uregion].first }}"
        AZ2: "{{ availability_zone[uregion].second }}"
        Environs: "{{ environs }}"
        Region: "{{ region }}"
        SecondOctet: "{{ second_octet[environs][uregion].vpc }}"
