---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.medium
    release: xenial
    stack_name: "{{ region }}-{{ stack }}-{{ environs }}-{{ spoke }}"
    uregion: "{{ region | regex_replace('-', '_') }}"
  tasks:
  - name: "Stack facts for {{ region }}-infra-{{ environs }}"
    cloudformation_stack_facts:
      stack_name: "{{ region }}-infra-{{ environs }}"
      region: "{{ region }}"
    register: stack_infra
  - name: "Provision {{ stack_name }}"
    cloudformation:
      region: "{{ region }}"
      stack_name: "{{ stack_name }}"
      state: "{{ stack_state }}"
      template: "{{ base_dir }}/cf_stack/{{ stack }}.yml"
      template_format: yaml
      template_parameters:
        AppName: "{{ stack }}"
        CohorsSecurityGroup: "{{ stack_infra.stack_outputs.SecurityGroup }}"
        Environs: "{{ environs }}"
        ExternalRouteTableId: "{{ stack_infra.stack_outputs.FirstPublicRouteTable }}"
        KeyName: "{{ key[environs][uregion] }}"
        ImageId: "{{ ami[release][uregion] }}"
        InternalRouteTableId: "{{stack_infra.stack_outputs.FirstPrivateRouteTable }}"
        InstanceType: "{{ instance_type }}"
        PublicDnsZone: "{{ public_dns_zone }}"
        Region: "{{ region }}"
        SecondVpnOctet: "{{ second_octet[environs][uregion].vpn }}"
        Spoke: "{{ spoke }}"
        SubnetId: "{{ stack_infra.stack_outputs.FirstPublicSubnet }}"
        VpcId: "{{ stack_infra.stack_outputs.Vpc }}"

