---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    stela_name: "dns"
  tasks:
  - name: "Provision {{ stela_name }}"
    cloudformation:
      region: "{{ region }}"
      stack_name: "{{ stela_name }}"
      state: "{{ stela_state }}"
      template: "{{ base_dir }}/stelae/{{ stela_name }}.yml"
      template_format: yaml
      template_parameters:
        Organization: "{{ organization }}"
        PublicDnsZone: "{{ public_dns_zone }}"
        PrivateDnsZone: "{{ private_dns_zone }}"
