---
- hosts: localhost
  connection: local
  gather_facts: False
#  vars_files:
#    - {{ base_dir }}/group_vars/all
  vars:
    release: xenial
    uregion: "{{ region | regex_replace('-', '_') }}"
  tasks:
  - name: "Provision {{ region }}-{{ stack }}-{{ environs }}"
    cloudformation:
      region: "{{ region }}"
      stack_name: "{{ region }}-{{ stack }}-{{ environs }}"
      state: present
      template: "{{ base_dir }}/cf/{{ region }}-{{ stack }}-{{ environs }}.cftemplate"
#      template_format: yaml
      template_parameters:
        AppName: "{{ stack }}"
        AZ1: "{{ availability_zone[uregion].first }}"
        AZ2: "{{ availability_zone[uregion].second }}"
        Environs: "{{ environs }}"
        Region: "{{ region }}"
        SecondOctet: "{{ second_octet[environs][uregion].vpc }}"
