---
- name: Standard APT Packages
  become: true
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - curl
    - dnsutils
    - iotop
    - python
    - wget
    - vim
