---
- hosts: consul_servers
  become: True
  gather_facts: True
  vars:
    consul_version: "0.6.4"
    consul_is_ui: true
    consul_is_server: true
    consul_datacenter: "{{ region }}-{{ environs }}"
    consul_dns_config: true
    consul_bootstrap: true
    consul_bind_address: "{{ ansible_default_ipv4['address'] }}"
    consul_use_systemd: true
    consul_ui_server_name: "{{ ansible_default_ipv4['address'] }} {{ region }}-{{ environs }}-consul.{{ private_dns_zone }} {{ ansible_fqdn }}" 
  roles:
    - { role: ansible-consul }
