---
Description: OpenVPN Server
Parameters:
  AppName:
    Type: String
  PublicDnsZone:
    Type: String
  PrivateDnsZone:
    Type: String
  CohorsSecurityGroup:
    Type: SecurityGroup
  Environs:
    Type: String
  ExternalRouteTableId:
    Type: AWS::EC2::RouteTable
  ImageId:
    Type: String
  InstanceType:
    Type: String
  InternalRouteTableId:
    Type: AWS::EC2::RouteTable
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  Region:
    Type: String
  SecondVpnOctet:
    Type: String
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  VpcId:
    Type: AWS::EC2::VPC::Id
Resources:
  VpnInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
      - Ref: SecurityGroup
      - Ref: CohorsSecurityGroup
      SourceDestCheck: 'False'
      SubnetId:
        Ref: SubnetId
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: VpnInstance
      Domain: vpc
  VpnServerDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Ref: DnsZone
      Name:
        Fn::Join:
        - ''
        - - Ref: VpcName
          - -vpn
          - "."
          - Ref: DnsZone
      ResourceRecords:
      - Ref: ElasticIp
      TTL: 300
      Type: A
  # VPN client access server routes
  IntRouteTableEntry:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock:
        Fn::Join:
        - ''
        - - '10.'
          - Ref: SecondVpnOctet
          - '.0.0/16'
      InstanceId:
        Ref: VpnInstance
      RouteTableId:
        Ref: InternalRouteTableId
  ExtRouteTableEntry:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock:
        Fn::Join:
        - ''
        - - '10.'
          - Ref: SecondVpnOctet
          - '.0.0/16'
      InstanceId:
        Ref: VpnInstance
      RouteTableId:
        Ref: ExternalRouteTableId
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: vpn-access-sg
      SecurityGroupEgress: []
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: UDP
        FromPort: '1194'
        ToPort: '1195'
      - CidrIp: 10.0.0.0/8
        IpProtocol: -1
        FromPort: '-1'
        ToPort: '-1'
      Tags:
      - Key: Name
        Value: vpn-access-sg
      VpcId:
        Ref: VpcId
Outputs:
  ExternalIp:
    Value:
      Ref: ElasticIp
