---
- name: "OpenVPN: Package dependences"
  become: true
  apt: 
    name="{{ item }}"
  with_items:
    - build-essential 
    - openssl
    - libssl-dev
    - lzop 
    - liblzo2-dev
    - libpam-dev

- name: "OpenVPN: Download src"
  become: yes
  get_url: >
    url=http://swupdate.openvpn.org/community/releases/openvpn-{{ openvpn_version }}.tar.gz
    dest=/usr/local/src/openvpn-{{ openvpn_version }}.tar.gz

- name: "OpenVPN: Extract and install OpenVPN"
  become: yes
  unarchive: src=/usr/local/src/openvpn-{{ openvpn_version }}.tar.gz
    dest=/usr/local/bin
    copy=no

- name: "OpenVPN: Enable IPv4 Forwarding: /etc/sysctl.conf"
  become: yes
  lineinfile: >
    dest=/etc/sysctl.conf
    state=present
    line=net.ipv4.ip_forward=1

- name: "OpenVPN: Enable IPv4 Forwarding Reload /etc/sysctl.conf"
  command:  sysctl -p

# iptables -t nat -A POSTROUTING -s 10.9.0.0/24 -o eth0 -j MASQUERADE
- name: "OpenVPN: Enable NAT IP Masquerading"
  become: yes
  iptables: >
    table=nat
    chain=POSTROUTING
    source=10.9.0.0/24
    out_interface=eth0
    jump=MASQUERADE

- name: "OpenVPN: Create /etc/openvpn/pki/issued"
  become: yes
  file: >
    path=/etc/openvpn/pki/issued
    mode=0755
    state=directory
    recurse=yes

- name: "OpenVPN: Create /etc/openvpn/pki/private"
  become: yes
  file: >
    path=/etc/openvpn/pki/private
    mode=0755
    state=directory
    recurse=yes

- name: "OpenVPN: /etc/openvpn/server.conf"
  become: yes
  vars:
    uregion: "{{ region | regex_replace('-', '_') }}"
  template: >
    src="{{ openvpn_server_conf_template }}"
    dest=/etc/openvpn/server.conf
    mode=0644

- name: "OpenVPN: /etc/openvpn/pki/ca.crt"
  become: yes
  copy: >
    src=../files/ca.crt
    dest=/etc/openvpn/pki/ca.crt
    mode=0644

- name: "OpenVPN: Copy /etc/openvpn/pki/issued/server.crt"
  become: yes
  copy: >
    src=../files/server.crt
    dest=/etc/openvpn/pki/issued/server.crt
    mode=0644

- name: "OpenVPN: /etc/openvpn/pki/private/server.key (SECRET)"
  become: yes
  copy: >
    src="{{ lookup('file', '../files/server.key') }}"
    dest=/etc/openvpn/pki/private/server.key
    mode=0600

- name: "OpenVPN: Copy /etc/openvpn/pki/dh.pem"
  become: yes
  copy: >
    src=../files/dh.pem
    dest=/etc/openvpn/pki/dh.pem
    mode=0644

- name: "OpenVPN: Start daemon"
  become: yes
  shell: daemon -- /usr/local/bin/openvpn --daemon --config /etc/openvpn/server.conf

